### PR TITLE
fix phpstorm inspection

### PR DESCRIPTION
**Pull request by ryo-endo**

### CODE REVIEW

**Comment by lqdung-lockon** [comment]
I merged. Arigatou Gozaimasu!!!

**Comment by ryo-endo** [comment]
@lqdung-lockon 
conflict PluginManager.php. Who will solve? (me or you)

**Comment by lqdung-lockon** [comment]
I merged by commit: https://github.com/eccubevn/Recommend-plugin/commit/b0d901db4ef065449902a7f7b3e128234f56164b

**Comment by ryo-endo** [comment]
i see. thkyou.
can i closed this PR ?

**Comment by lqdung-lockon** [comment]
Yes.

**Comment by ryo-endo** [comment]
別で取込み済みなので、これはCLOSEする。

**Pull request closed without merging**
